version: "3.9"
services:
 web:
  build: ./web
  image: "imageweb"
  ports:
   - 80:80
   - 443:443
  links:
   - "db:db_container"
  container_name: "kadaiweb_container"
   
 db:
  build: ./db
  image: "imagedb"
  ports: 
   - 4306:3306
  expose:
   - 3306
  container_name: "db_container"
  volumes:
   - kadai:/var/lib/mysql
   
volumes:
 kadai: 